version: '3'

services:
  redis:
    build: ./redis/.
    ports:
      - "6379:6379"
    networks:
      - one_net
  backend:
    build: ./backend/.
    ports:
      - "8000:8000"
    volumes:
      - "static:/usr/src/Dashboard/static"
    networks:
      - one_net
  nginx:
    build: ./nginx/.
    ports:
      - "8080:80"
    volumes:
      - "static:/static"
    depends_on:
      - backend
    links:
      - "backend:backend"
    networks:
      - one_net
volumes:
  static:
networks:
  one_net:
    driver: bridge
