version: '3'

services:
  nginx:
    build: ./nginx/.
    ports:
      - "8080:80"
    networks:
      - one_net
  redis:
    build: ./redis/.
    ports:
      - "6379:6379"
    networks:
      - one_net
  backend:
    build: ./backend/.
    ports:
      - "8000:8000"
    networks:
      - one_net
    depends_on:
      - nginx
networks:
  one_net:
    driver: bridge
